// example/react-demo/src/App.js
import React from 'react'
import Quill from 'quill'
import QuillImageDropAndPaste from 'quill-image-drop-and-paste'

import 'quill/dist/quill.snow.css'

export default class App extends React.Component {

  constructor(props) {
    super(props)
    this.state = {
      quill: null,
      image: {
        type: '', // image's mimeType
        dataUrl: null, // image's base64 string
        blob: null, // image's BLOB object
        file: null, // image's File object
      }
    }
  }

  componentDidMount() {
    Quill.register('modules/imageDropAndPaste', QuillImageDropAndPaste)
    const quill = new Quill('#editor-container', {
      modules: {
        toolbar: [['bold', 'italic'], ['link', 'image']],
        imageDropAndPaste: {
          handler: this.imageHandler.bind(this)
        }
      },
      placeholder: 'Copy & paste, or drag an image here...',
      readOnly: false,
      theme: 'snow'
    })
    this.setState({ quill })
  }

  imageHandler(dataUrl, type, imageData) {
    imageData.minify({
      maxWidth: 320,
      maxHeight: 320,
      quality: .7
    }).then((miniImageData) => {
      const blob = miniImageData.toBlob()
      const file = miniImageData.toFile('my_cool_image.png')

      console.log(`type: ${type}`)
      console.log(`dataUrl: ${dataUrl}`)
      console.log(`blob: ${blob}`)
      console.log(`file: ${file}`)

      this.setState({ image: { type, dataUrl, blob, file } })
    })
  }

  render() {
    const { image } = this.state

    return (
      <div className="App">
        <h1>React Example</h1>
        <div id="editor-container" style={{ height: '320px' }}></div>
        
        <div>
          <h4>Preview image from BLOB URL:</h4>
          { image.blob &&
            <img src={URL.createObjectURL(image.blob)} alt="preview blob" />
          }
        </div>
        
        <hr />
        
        <div>
          <h4>Get file infomation from File Object:</h4>
          { image.file &&
            <div>
              <b>name:</b> <span>{image.file.name}</span> <br />
              <b>size:</b> <span>{image.file.size}</span> <br />
              <b>type:</b> <span>{image.file.type}</span>
            </div>
          }
        </div>
      </div>
    )
  }
}

// example/angular-demo/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { DomSanitizer, SafeUrl } from '@angular/platform-browser';
import Quill from 'quill';
import QuillImageDropAndPaste, { ImageData as QuillImageData } from 'quill-image-drop-and-paste';

interface IImageMeta {
  type: string;
  dataUrl: string;
  blobUrl: SafeUrl;
  file: File | null;
}

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent implements OnInit {
  title = 'Angular Example';
  image: IImageMeta = {
    type: '',
    dataUrl: '',
    blobUrl: '',
    file: null,
  };

  constructor(private sanitizer: DomSanitizer) {}

  imageHandler(dataUrl: string, type: string, imageData: QuillImageData) {
    imageData
      .minify({
        maxWidth: 320,
        maxHeight: 320,
        quality: 0.7,
      })
      .then((miniImageData) => {
        if (miniImageData instanceof QuillImageData) {
          const blob = miniImageData.toBlob();
          const file = miniImageData.toFile('my_cool_image.png');

          console.log(`type: ${type}`);
          console.log(`dataUrl: ${dataUrl}`);
          console.log(`blob: ${blob}`);
          console.log(`file: ${file}`);

          this.image = {
            type,
            dataUrl,
            blobUrl: this.sanitizer.bypassSecurityTrustUrl(URL.createObjectURL(blob)),
            file,
          };
        }
      });
  }

  ngOnInit() {
    Quill.register('modules/imageDropAndPaste', QuillImageDropAndPaste);
    new Quill('#editor-container', {
      modules: {
        toolbar: [
          ['bold', 'italic'],
          ['link', 'image'],
        ],
        imageDropAndPaste: {
          handler: this.imageHandler.bind(this),
        },
      },
      placeholder: 'Copy & paste, or drag an image here...',
      readOnly: false,
      theme: 'snow',
    });
  }
}

<div class="app-container">
  <h1>{{title}}</h1>
  <div id="editor-container"></div>

  <div>
    <h4>Preview image from BLOB URL:</h4>
    <img *ngIf="image.blobUrl" [src]="image.blobUrl" alt="preview blob" />

    <hr />
        
    <div>
      <h4>Get file infomation from File Object:</h4>
      <div *ngIf="image.file">
        <b>name:</b> <span>{{image.file.name}}</span> <br />
        <b>size:</b> <span>{{image.file.size}}</span> <br />
        <b>type:</b> <span>{{image.file.type}}</span>
      </div>
    </div>
  </div>
  
  <hr />
  
</div>
